name: monkeytype-stats
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Monkeytype Readme
        uses: monkeytype-hub/monkeytype-readme@master
        with:
          # ASEGÚRATE de que este sea tu usuario EXACTO en Monkeytype
          MONKEYTYPE_USERNAME: 'clemente_abarzua'
          MONKEYTYPE_THEME_NAME: 'nord'
