name: monkeytype-stats
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Monkeytype Readme
        uses: monkeytype-hub/monkeytype-readme@master
        with:
          # Nombres de variables corregidos para esta versión del bot
          username: 'clemente_abarzua'
          themes: 'nord'
          github-token: ${{ secrets.GITHUB_TOKEN }}
